services:
  - type: web
    name: syb-api
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NODE_ENV
        value: production
      - key: VITE_SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ADMIN_JWT_SECRET
        sync: false
      - key: VITE_DEPOSIT_ADDRESS
        sync: false
